# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AddField(
            model_name='image',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
